### ISSUE TITLE
Document that OxygenLibrary needs to be imported in all suite files

### ISSUE THREAD

**Issue by niecore** [eficode/robotframework-oxygen#17]
When running tests I get the following error: 

`[ ERROR ] Calling method 'end_test' of listener 'oxygen.listener' failed: No library 'oxygen.OxygenLibrary' found.`

**Comment by Tattoo** [comment]
@niecore can you share your test case how you are using the library? You can also refer to [example](https://github.com/eficode/robotframework-oxygen/tree/master/example) provided

**Comment by niecore** [comment]
I found out, that the library needs to be imported for every file that contains test when the listener is active.
Even when there are no Keywords used from the oxygen library.

You can simply reproduce this by calling robotframework with the oxygen listener on a test suite that does not import the library.

**Comment by Tattoo** [comment]
Ah yes, that is correct and by design, as Oxygen will check every test case if it uses the library or not.

Will clarify this in documentation.

**Comment by Tattoo** [comment]
@niecore just to let you know, we managed to fix this completely in version 0.2 which was released yesterday :)

**Comment by niecore** [comment]
@Tattoo Thank you :)
