### ISSUE TITLE
Add CLI option to overwrite handler configurations

### ISSUE THREAD

**Issue by mikkilevon** [eficode/robotframework-oxygen#2]
There should be an option in CLI to overwrite f.ex Zap accepted_risk_level to be 1 instead of the default 2

**Comment by matejc** [comment]
Solution 1: https://github.com/eficode/robotframework-oxygen/pull/24
Solution 2: https://github.com/eficode/robotframework-oxygen/pull/23

**Comment by Tattoo** [comment]
Fixed in #23
