### ISSUE TITLE
Support html in log messages

### ISSUE THREAD

**Issue by FummiTaksi** [eficode/robotframework-oxygen#6]
If you add html formatted message to your test report following documentation: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#logging-example the message will not appear correctly in the log file:  
![image](https://user-images.githubusercontent.com/14012418/86895951-e6d9f200-c10d-11ea-87e5-17836b2c7097.png)

**Comment by Tattoo** [comment]
this was resolved by #8 and #10 , gracias @FummiTaksi!
